---
abstract: 'postgresql runner for tests'
author:
  - 'Kazuho Oku'
build_requires:
  DBD::Pg: 0
  DBI: 0
  ExtUtils::MakeMaker: 6.42
  Test::SharedFork: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-postgresql
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Lite: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
