version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    environment:
      - DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
          name: install system dependencies
          command: apt-get update && apt-get install -y sudo git postgresql libpq-dev build-essential cpanminus
      - checkout
      - run:
          name: install CPAN dependencies
          command: cpanm --notest --installdeps .
      - run:
          name: Test module
          command: cpanm --no-interactive --test-only --verbose .
